### ISSUE TITLE
Content to code 

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/content-to-code#1]
1. body - wraps all HTML elements rendered on the screen
2. h1 - heading level 1, most important piece of content on the page
3. time datetime - marks date of publication; datetime is the machine readable version
4. p - a generic paragraph of text
5. video - embedded media (video)
6. h2 - heading level 2
7. p - a generic paragraph of text
8. em - emphasizing text (ticket pricing)
9. data value - numerical data and the computer readable information
10. data value - numerical data and the computer readable information
11. a - hyperlink to another page
12. h2 - heading level 2
13. section - a group of related content with a heading
14. p - a generic paragraph of text
15. h2 - heading level 2
16. section - a group of related content with a heading
17. dt - description term
18. dd - description definition
19. h2 - heading level 2
20. blockquote - stand alone quote
21. q - quote
22. p - a generic paragraph of text 
23. cite - source of the quote
24. h2 - heading level 2
25. address - contact information/ postal address

@thomasjbradley

**Comment by thomasjbradley** [comment]
Looks great! A few corrections:

>1. body - wraps all HTML elements rendered on the screen

I’d probably make this the `<main>` tag.

>14. p - a generic paragraph of text

For this one, I’d use a `<li>` inside a `<ol>` because it’s a list & they’re in alphabetical order.

>21. q - quote

This would just be a generic `<p>` tag because we don’t need a `<q>` inside `<blockquote>`—it’s doubling up

>22. p - a generic paragraph of text

It’s convention to use a `<footer>` in this situation because it wraps the “less important” information of the `<blockquote>`
